### ISSUE TITLE
Repository is incompatible with WoWUp

### ISSUE THREAD

**Issue by KevinTyrrell** [LenweSaralonde/MessageQueue#1]
Installing MessageQueue for TBC using WoWUp by inputting the URL of this repository yields the following error:

![image](https://user-images.githubusercontent.com/12791400/168793831-75f4ed2a-dbc6-4cfe-8585-6f6dc0a1e1c6.png)

Given the popularity of WoWUp and the lack of Curseforge as an option, it is highly recommended you make this repository compatible with WoWUp in order to allow ease-of-use when installing.

**Comment by LenweSaralonde** [comment]
Please post the URL you pasted here so I can try on my side.

**Comment by KevinTyrrell** [comment]
[https://github.com/LenweSaralonde/MessageQueue](https://github.com/LenweSaralonde/MessageQueue)

A working example of another addon would be the following url (this url will cause AtlasLoot TBC to be installed)

[https://github.com/Hoizame/AtlasLootClassic](https://github.com/Hoizame/AtlasLootClassic)

**Comment by jliddev** [comment]
This is a WowUp bug, feel free to close.

**Comment by KevinTyrrell** [comment]
> This is a WowUp bug, feel free to close.

May I ask how this is a WoWUp bug? I've tried numerous other GitHub repositories and they all are imported without issue. This repository however seems to be an exception.

**Comment by LenweSaralonde** [comment]
I tried with the latest WowUp on a fresh WoW instance used for testing and I was able to install the addon without any issue.
It could also have been a temporary issue with GitHub because I haven't done anything on my side.

**Comment by KevinTyrrell** [comment]
> I tried with the latest WowUp on a fresh WoW instance used for testing and I was able to install the addon without any issue. It could also have been a temporary issue with GitHub because I haven't done anything on my side.

I just reinstalled WoWUp and downloaded the most recent beta client (2.8.2-beta.3). I repeated the same installation steps and had the following error instead:
![image](https://user-images.githubusercontent.com/12791400/170107094-10bd9e8d-eca2-408f-aaf7-97891ba9f80c.png)

You can hide this error and install the addon but clearly WoWUp encourages the `-bc` tag to be added at the end of release zips in order for it to distinguish classic/tbc/retail versions apart from each other. 

I believe this guide explains the naming format for release files, which would hopefully halt the errors from appearing: https://wowup.io/guide/wowup/curseforge-migration

**Comment by LenweSaralonde** [comment]
That's the same release and .zip file for all 3 WoW versions. It has a .toc for each version.

**Comment by KevinTyrrell** [comment]
> That's the same release and .zip file for all 3 WoW versions. It has a .toc for each version.

I understand, but in order for the WoWUp software to recognize this repository as a TBC addon, the [Release](https://github.com/LenweSaralonde/MessageQueue/releases/tag/0.5.1) must have a `.zip` file whose file name ends with `-bcc`. For example `MessageQueue1.0-bcc.zip`.

[Here's an example](https://github.com/ForsakenNGS/LogTracker_CharacterData_US/releases/tag/1.0.2-202205252201) of how another addon has its release. You can see how he has multiple versions in one release, one with `-bcc` (burning crusade) and one without it (retail).

**Comment by LenweSaralonde** [comment]
> in order for the WoWUp software to recognize this repository as a TBC addon, the [Release](https://github.com/LenweSaralonde/MessageQueue/releases/tag/0.5.1) must have a `.zip` file whose file name ends with `-bcc`. For example `MessageQueue1.0-bcc.zip`

AFAIK, there is no standard way to name .zip files for GitHub add-on releases, especially those that support the 3 WoW versions. The popup is just here to warn the user that it might not be a must-version release file, since the WowUp client has now way to see what's inside the .zip without downloading it, the the install actually works as intended.
